language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
env:
  - DB=postgresql
before_script:
  - npm install -g grunt-cli && sudo -u postgres psql -c "CREATE DATABASE raat;" && sudo -u postgres psql -c "CREATE USER raat_user WITH password 'Jnm43dUJs';" && sudo -u postgres psql -c "GRANT ALL privileges ON DATABASE raat TO raat_user;"
    DATABASE_URL=pg://raat_user:Jnm43dUJs@localhost:5432/raat ./node_modules/.bin/pg-migrate up
services:
  - redis-server